services:
  receipt-processor:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/receipt-processor
    working_dir: /receipt-processor
    command: bash -c "npm upgrade && npm update && npm install && npm start"
