version: "3.8"

services:
  receipt-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/receipt-processor
    command: npm start
